export const currency = '$';
export const currentYear = new Date().getFullYear();
export const appName = 'Job Portal';
export const appTitle = 'Job Portal Admin Dashboard';
export const appDescription = 'Project management tools, web Dashboard, and powerful features.';
export const author = 'Job Portal';
export const authorWebsite = 'https://innovativemodernengineers.com/';
export const authorContact = '';
export const basePath = '';